version: 2
updates:
  - package-ecosystem: npm
    directory: /site
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: swift
    directory: /FoodMapper.xcodeproj/project.xcworkspace/xcshareddata/swiftpm
    schedule:
      interval: weekly
